version: '3.8'

services:
  db:
    container_name: spring-boot-blueprint-db
    image: postgres:15.0-alpine3.16
    environment:
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: spring-boot-blueprint
      PGDATA: /var/lib/postgresql/data/db-files/
    volumes:
      - type: volume
        source: spring-boot-blueprint-db-volume
        target: /var/lib/postgresql/data
    ports:
      - "5432:5432"
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s

volumes:
  spring-boot-blueprint-db-volume:
    name: spring-boot-blueprint-db
